### ISSUE TITLE
Unable to get info for Schedule ID

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#41] opened 2023-03-21 13:00 UTC
### Description

When tried to fetch schedule info on testnet got below response
**query with no payment transaction failed pre-check with status `InvalidScheduleId`**

### Steps to reproduce

`let info = try await ScheduleInfoQuery()
            .scheduleId(scheduleID)
            .execute(client)`

### Hedera network

testnet

### Version

v0.15.0

### Operating system

macOS

**Comment by izik1** [comment] 2023-03-21 23:06
While debugging this I certainly found _a_ bug (scheduled transaction IDs have a parsing bug), but... After patching the other bug, I can't reproduce _this_ one, I used the following code:

```swift
import Hedera
import Foundation

@main
public enum Program {
    public static func main() async throws {
        let client = try Client.forTestnet()

        client.setOperator("<my account ID>", "<my key>")

        let scheduleId = try await ScheduleCreateTransaction()
            .scheduledTransaction(
                TransferTransaction()
                    .hbarTransfer(env.operatorAccountId, 1)
                    .hbarTransfer("0.0.98", -1)
                    .freezeWith(client)
            )
            .expirationTime(.now + .hours(1))
            .isWaitForExpiry(true)
            .execute(client)
            .getReceipt(client)
            .scheduleId!

        print(scheduleId)

        print(try await ScheduleInfoQuery(scheduleId: scheduleId).execute(client))
    }
}
```

Which printed something along these lines (note the lack of errors errors):
```
0.0.3892056
Hedera.ScheduleInfo
```

**Comment by SimiHunjan** [comment] 2023-04-12 17:44
@nirmalpatidar123 can we close this issue?

**Comment by SimiHunjan** [comment] 2023-05-01 18:21
Closing issue for now. Please reopen if you are still experiencing the issue.

**Closed by SimiHunjan** 2023-05-01 18:21 UTC
Labels: bug
